server:
  port: 9902
spring:
  application:
    name: gateway
  profiles:
    active: router
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  main:
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9901/eureka/





